### ISSUE TITLE
[feat] User Entity 개발

### ISSUE THREAD

**Issue by gmlrude** [Techeer-3rd-COKKIRI/backend#4]
## ✨ 구현 할 기능
user entity 개발하기

## 📢 구현 방식
JPA를 사용한 entity 개발

### 고려해볼 사항
- is_deleted(삭제여부)나 is_end(종료여부) 컬럼 default값으로 false 고려
 - `@Column(columnDefinition = "boolean default false")` 으로 사용
- 위의 사항이 가능하다면 `@Builder` 어노테이션을 객체 클래스 전체에 적용하는 방법도 고려 -> 코드 간결화 가능 

<br>

### 📕 래퍼런스
https://velog.io/@yu-jin-song/SpringBoot-게시판-구현-1-Entity-및-Repository-구현
<컬럼 기본값 설정>
https://www.baeldung.com/jpa-default-column-values

**Comment by JeongHunHui** [comment]
> s_deleted(삭제여부)나 is_end(종료여부) 컬럼 default값으로 false 고려
> @Column(columnDefinition = "boolean default false") 으로 사용

-> 좀 찾아보고 생각을 해봤는데, 확실히 좋은거같아요!

> 위의 사항이 가능하다면 @Builder 어노테이션을 객체 클래스 전체에 적용하는 방법도 고려 -> 코드 간결화 가능

-> is_deleted를 기본값으로 할당해준다고 해도 생성자를 따로 만들고 @Builder를 달아주면 좋은점이 @Builder로 건드리면 안되는 값(ex: id, 수정 및 생성일자 등)을 못건드리게 할 수 있어서 라서, 이부분은 그냥 기존 방식대로 해야할거 같아요!

**Comment by JeongHunHui** [comment]
그리고, 오른쪽에보면 이슈에 브랜치를 할당해줄 수 있는데, 그러면 pull request 머지 될때 알아서 이슈도 닫혀서 연결하면 좋을거 같아요!
<img width="322" alt="image" src="https://user-images.githubusercontent.com/108508730/204963811-3ea9ac56-3341-4d72-adfa-b2630fbebc4b.png">
