### ISSUE TITLE
[feat] Study 엔티티 구현

### ISSUE THREAD

**Issue by kjeongh** [Techeer-3rd-COKKIRI/backend#6]
## ✨ 구현 할 기능
Study엔티티 구현

## 📢 구현 방식

<br>

### 📕 래퍼런스

**Comment by JeongHunHui** [comment]
이슈 제목에 내용을 넣어주세요..!
ex) [feat] Study엔티티 구현
그리고, 오른쪽에보면 이슈에 브랜치를 할당해줄 수 있는데, 그러면 pull request 머지 될때 알아서 이슈도 닫혀서 연결하면 좋을거 같아요!
<img width="318" alt="image" src="https://user-images.githubusercontent.com/108508730/204963524-347193a6-fefa-4d58-80a9-2625de409c40.png">
